# Form implementation generated from reading ui file 'confirm_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(565, 357)
        self.confirmation_label = QtWidgets.QLabel(parent=Dialog)
        self.confirmation_label.setGeometry(QtCore.QRect(40, 30, 441, 31))
        self.confirmation_label.setObjectName("confirmation_label")
        self.confirm_button = QtWidgets.QPushButton(parent=Dialog)
        self.confirm_button.setGeometry(QtCore.QRect(10, 280, 211, 28))
        self.confirm_button.setObjectName("confirm_button")
        self.cancel_button = QtWidgets.QPushButton(parent=Dialog)
        self.cancel_button.setGeometry(QtCore.QRect(270, 280, 211, 28))
        self.cancel_button.setObjectName("cancel_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.confirmation_label.setText(_translate("Dialog", "Текст"))
        self.confirm_button.setText(_translate("Dialog", "Подтвердите действие"))
        self.cancel_button.setText(_translate("Dialog", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
